import { describe, expect, it } from 'vitest';
import { render, screen } from '@solidjs/testing-library';

import RoadmapRoute from './Roadmap';

describe('RoadmapRoute', () => {
  it('renders the public roadmap as a main website route', () => {
    render(() => <RoadmapRoute />);

    expect(screen.getByRole('heading', { name: /what shipped/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Memory' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /Operations are visible/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Time-native' })).toBeInTheDocument();
    expect(screen.getByText('Scheduled events on Home')).toBeInTheDocument();
    expect(screen.getByText('Vault memory previews')).toBeInTheDocument();
    expect(screen.getByText('Quiet room activity')).toBeInTheDocument();
    expect(screen.getByText('Home return recaps')).toBeInTheDocument();
    expect(screen.getByText('Spotlight handoff')).toBeInTheDocument();
    expect(screen.getByText('Room rhythm heatlines')).toBeInTheDocument();
    expect(screen.getByText('Event context')).toBeInTheDocument();
    expect(screen.getByText('Review from start')).toBeInTheDocument();
    expect(screen.getByText('Catch-up review history')).toBeInTheDocument();
    expect(screen.getByText('Review text search')).toBeInTheDocument();
    expect(screen.getByText('Channel directory dedupe')).toBeInTheDocument();
    expect(screen.getByText('Reader digest notes')).toBeInTheDocument();
    expect(screen.getByText('Shareable moment links')).toBeInTheDocument();
    expect(screen.getByText('Reader memory context')).toBeInTheDocument();
    expect(screen.getByText('Moment search handoff')).toBeInTheDocument();
    expect(screen.getByText('Reader transcript jumps')).toBeInTheDocument();
    expect(screen.getByText('Digest review handoff')).toBeInTheDocument();
    expect(screen.getByText('Review completion')).toBeInTheDocument();
    expect(screen.getByText('Reader return Home')).toBeInTheDocument();
    expect(screen.getByText('Reviewed span recall')).toBeInTheDocument();
    expect(screen.getByText('Hydrated context trails')).toBeInTheDocument();
    expect(screen.getByText('Vault context trails')).toBeInTheDocument();
    expect(screen.getByText('Vault anchor jumps')).toBeInTheDocument();
    expect(screen.getByText('Command grammar examples')).toBeInTheDocument();
    expect(screen.getByText('Selected-command status')).toBeInTheDocument();
    expect(screen.getByText('Join/open aliases')).toBeInTheDocument();
    expect(screen.getByText('Goto-at jump')).toBeInTheDocument();
    expect(screen.getByText('Targeted at jump')).toBeInTheDocument();
    expect(screen.getByText('Search/find grammar')).toBeInTheDocument();
    expect(screen.getByText('Reader command')).toBeInTheDocument();
    expect(screen.getByText('Density commands')).toBeInTheDocument();
    expect(screen.getByText('Width commands')).toBeInTheDocument();
    expect(screen.getByText('Motion commands')).toBeInTheDocument();
    expect(screen.getByText('Timed mute')).toBeInTheDocument();
    expect(screen.getByText('Quiet on/off')).toBeInTheDocument();
    expect(screen.getByText('J/K transcript nav')).toBeInTheDocument();
    expect(screen.getByText('Client access audit')).toBeInTheDocument();
    expect(screen.getByText('Dense-panel evidence')).toBeInTheDocument();
    expect(screen.getByText('Home access evidence')).toBeInTheDocument();
    expect(screen.getByText('Search access evidence')).toBeInTheDocument();
    expect(screen.getByText('Inbox access evidence')).toBeInTheDocument();
    expect(screen.getByText('Directory access evidence')).toBeInTheDocument();
    expect(screen.getByText('Account access evidence')).toBeInTheDocument();
    expect(screen.getByText('Sidebar access evidence')).toBeInTheDocument();
    expect(screen.getByText('Shortcuts access evidence')).toBeInTheDocument();
    expect(screen.getByText('Command palette evidence')).toBeInTheDocument();
    expect(screen.getByText('Pins access evidence')).toBeInTheDocument();
    expect(screen.getByText('Theme import evidence')).toBeInTheDocument();
    expect(screen.getByText('Thread access evidence')).toBeInTheDocument();
    expect(screen.getByText('Voice settings evidence')).toBeInTheDocument();
    expect(screen.getByText('Call overlay evidence')).toBeInTheDocument();
    expect(screen.getByText('Message action evidence')).toBeInTheDocument();
    expect(screen.getByText('Member list evidence')).toBeInTheDocument();
    expect(screen.getByText('Notification control evidence')).toBeInTheDocument();
    expect(screen.getByText('Time scrubber evidence')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Torii entry' })).toBeInTheDocument();
    expect(screen.getByText('Rich invite route')).toBeInTheDocument();
    expect(screen.getByText('Invite Open Graph metadata')).toBeInTheDocument();
    expect(screen.getByText('Install guide')).toBeInTheDocument();
    expect(screen.getByText('Generated public sitemap')).toBeInTheDocument();
    expect(screen.getByText('Public glossary')).toBeInTheDocument();
    expect(screen.getByText('Native onboarding forms')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Venue model' })).toBeInTheDocument();
    expect(screen.getByText('Named conversations')).toBeInTheDocument();
    expect(screen.getByText('Forum topic follow controls')).toBeInTheDocument();
    expect(screen.getByText('Pinned forum projection')).toBeInTheDocument();
    expect(screen.getByText('Compact calm preset control')).toBeInTheDocument();
    expect(screen.getByText('Mobile Home tab')).toBeInTheDocument();
    expect(screen.getByText('Touch-sized Home review cards')).toBeInTheDocument();
    expect(screen.getByText('Quiet boost Home digest')).toBeInTheDocument();
    expect(screen.getByText('Scheduled event header chip')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Atmosphere' })).toBeInTheDocument();
    expect(screen.getByText('User reduced-transparency control')).toBeInTheDocument();
    expect(screen.getByText('Mobile drawer focus management')).toBeInTheDocument();
    expect(screen.getByText('Mobile drawer focus trap')).toBeInTheDocument();
    expect(screen.getByText('Deterministic time scrubber jumps')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Media presence' })).toBeInTheDocument();
    expect(screen.getByText('Voice room status chip')).toBeInTheDocument();
    expect(screen.getByText('Spatial audio availability state')).toBeInTheDocument();
    expect(screen.getByText('Watch-together surface')).toBeInTheDocument();
    expect(screen.getByText('Watch-together room activity')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Apps' })).toBeInTheDocument();
    expect(screen.getByText('Block-Kit-lite renderer')).toBeInTheDocument();
    expect(screen.getByText('Block-Kit-lite message controls')).toBeInTheDocument();
    expect(screen.getByText('Capability-scoped extension actions')).toBeInTheDocument();
    expect(screen.getByText('Reviewed portable import')).toBeInTheDocument();
    expect(screen.getByText('Server snapshot imports')).toBeInTheDocument();
    expect(screen.getByText('IRC-log-to-vault import')).toBeInTheDocument();
    expect(screen.getByText('Integrations page')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Local intelligence' })).toBeInTheDocument();
    expect(screen.getByText('AI provenance chrome')).toBeInTheDocument();
    expect(screen.getByText('Search provenance labels')).toBeInTheDocument();
    expect(screen.getByText('Digest provenance labels')).toBeInTheDocument();
    expect(screen.getByText('Caption provenance labels')).toBeInTheDocument();
    expect(screen.getByText('Extension action audit')).toBeInTheDocument();
    expect(screen.getByText('Agent safety page')).toBeInTheDocument();
    expect(screen.getByText('Provenance labels')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Roaming' })).toBeInTheDocument();
    expect(screen.getByText('TravelTo vault fallback')).toBeInTheDocument();
    expect(screen.getAllByText('Active-target vault search').length).toBeGreaterThan(0);
    expect(screen.getByText('Installable manifest')).toBeInTheDocument();
    expect(screen.getByText('PWA shortcuts')).toBeInTheDocument();
    expect(screen.getByText('Portable vault export')).toBeInTheDocument();
    expect(screen.getByText('Portable vault import')).toBeInTheDocument();
    expect(screen.getByText('Reviewed catch-up transfer')).toBeInTheDocument();
    expect(screen.getByText('Room draft transfer')).toBeInTheDocument();
    expect(screen.getByText(/time is active/i)).toBeInTheDocument();
    expect(screen.getByText('complete phases').closest('.data-metric')).toHaveTextContent('4');
    expect(screen.getByRole('heading', { name: 'Washi' })).toBeInTheDocument();
  });

  it('links to the rest of the public website', () => {
    render(() => <RoadmapRoute />);
    const hrefs = screen.getAllByRole('link').map((a) => a.getAttribute('href'));

    expect(hrefs).toContain('/stats');
    expect(hrefs).toContain('/status');
    expect(hrefs).toContain('/app');
    expect(hrefs).toContain('/accessibility/');
    expect(hrefs).toContain('/invite?join=%23root');
    expect(hrefs).toContain('/glossary/');
    expect(hrefs).toContain('/integrations/');
    expect(hrefs).toContain('/agents/');
  });
});
