module ThemeTokens exposing (themeIds, tokensFor)

{-| Built-in theme token maps — generated from `src/theme/themes.ts`.

Do not hand-edit: regenerate from the oracle. Each map is the full
literal token set (`THEMES[id].tokens`); the studio overlays session
overrides on top via `Studio.diffOverrides` / `Studio.customThemeTokens`.
-}

import Dict exposing (Dict)


{-| All 18 built-in theme ids, oracle order. -}
themeIds : List String
themeIds =
    [ "ocean"
    , "tide"
    , "abyss"
    , "reef"
    , "onyx"
    , "obsidian"
    , "pearl"
    , "ink"
    , "shu"
    , "hisui"
    , "pine"
    , "kohaku"
    , "terracotta"
    , "vermillion"
    , "sapphire"
    , "teal"
    , "slate"
    , "frost"
    ]


{-| Full token map for a built-in theme id (`Dict.empty` when unknown). -}
tokensFor : String -> Dict String String
tokensFor id =
    case id of
        "ocean" ->
            Dict.fromList
                [ ( "--ink", "#202429" )
                , ( "--ink-2", "#262c32" )
                , ( "--stone", "#2d333a" )
                , ( "--stone-2", "#343b43" )
                , ( "--stone-3", "#3a424b" )
                , ( "--stone-line", "#49535e" )
                , ( "--lapis", "#65adf5" )
                , ( "--lapis-bright", "#65adf5" )
                , ( "--lapis-deep", "#397db8" )
                , ( "--gold", "#b4bfca" )
                , ( "--gold-bright", "#f5f7f8" )
                , ( "--gold-deep", "#71808e" )
                , ( "--brand-action", "#ff987d" )
                , ( "--shu", "#ff6f61" )
                , ( "--shu-bright", "#ff9484" )
                , ( "--paper", "#f5f7f8" )
                , ( "--paper-dim", "#b4bfca" )
                , ( "--paper-mute", "#b4bfca" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 28%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 12%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 40%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--paper) 6%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "4px" )
                , ( "--r-md", "8px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "220ms" )
                ]
        "tide" ->
            Dict.fromList
                [ ( "--ink", "#00060b" )
                , ( "--ink-2", "#000a11" )
                , ( "--stone", "#051820" )
                , ( "--stone-2", "#12262e" )
                , ( "--stone-3", "#21343d" )
                , ( "--stone-line", "#254350" )
                , ( "--lapis", "#00b8ed" )
                , ( "--lapis-bright", "#9ae0ff" )
                , ( "--lapis-deep", "#007093" )
                , ( "--gold", "#5dcbd1" )
                , ( "--gold-bright", "#92f1f6" )
                , ( "--gold-deep", "#3e999d" )
                , ( "--shu", "#ff7a6c" )
                , ( "--shu-bright", "#ffa193" )
                , ( "--paper", "#d1e1e9" )
                , ( "--paper-dim", "#8c9ba2" )
                , ( "--paper-mute", "#536770" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 50%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 20%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 16%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--paper) 8%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "6px" )
                , ( "--r-md", "12px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "260ms" )
                ]
        "abyss" ->
            Dict.fromList
                [ ( "--ink", "#000102" )
                , ( "--ink-2", "#000103" )
                , ( "--stone", "#010508" )
                , ( "--stone-2", "#050c10" )
                , ( "--stone-3", "#0c1418" )
                , ( "--stone-line", "#101c22" )
                , ( "--lapis", "#0091cb" )
                , ( "--lapis-bright", "#58c4ff" )
                , ( "--lapis-deep", "#005477" )
                , ( "--gold", "#51a0ad" )
                , ( "--gold-bright", "#88cedb" )
                , ( "--gold-deep", "#236671" )
                , ( "--shu", "#f0594b" )
                , ( "--shu-bright", "#ff7c6e" )
                , ( "--paper", "#d4e0e8" )
                , ( "--paper-dim", "#8f9aa1" )
                , ( "--paper-mute", "#56666f" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 36%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 13%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 11%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--paper) 5%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "3px" )
                , ( "--r-md", "8px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "reef" ->
            Dict.fromList
                [ ( "--ink", "#000407" )
                , ( "--ink-2", "#00060a" )
                , ( "--stone", "#010f16" )
                , ( "--stone-2", "#081a21" )
                , ( "--stone-3", "#13252c" )
                , ( "--stone-line", "#142f3b" )
                , ( "--lapis", "#0094bc" )
                , ( "--lapis-bright", "#0bc9ff" )
                , ( "--lapis-deep", "#00556e" )
                , ( "--gold", "#f19173" )
                , ( "--gold-bright", "#ffc0ac" )
                , ( "--gold-deep", "#a9573d" )
                , ( "--shu", "#ff6f5e" )
                , ( "--shu-bright", "#ff9a86" )
                , ( "--paper", "#d2e1e8" )
                , ( "--paper-dim", "#8d9ba2" )
                , ( "--paper-mute", "#54676f" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 16%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "5px" )
                , ( "--r-md", "11px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "260ms" )
                ]
        "onyx" ->
            Dict.fromList
                [ ( "--ink", "#000101" )
                , ( "--ink-2", "#010203" )
                , ( "--stone", "#050709" )
                , ( "--stone-2", "#0d0f12" )
                , ( "--stone-3", "#16191c" )
                , ( "--stone-line", "#1e2226" )
                , ( "--lapis", "#6996c5" )
                , ( "--lapis-bright", "#9cc2ea" )
                , ( "--lapis-deep", "#385b7e" )
                , ( "--gold", "#c9a24a" )
                , ( "--gold-bright", "#f1d489" )
                , ( "--gold-deep", "#8c6c2c" )
                , ( "--shu", "#e95145" )
                , ( "--shu-bright", "#ff7f71" )
                , ( "--paper", "#eae8e0" )
                , ( "--paper-dim", "#a4a19a" )
                , ( "--paper-mute", "#6e6c63" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--gold) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--gold) 15%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 13%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--paper) 6%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "4px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "obsidian" ->
            Dict.fromList
                [ ( "--ink", "#000001" )
                , ( "--ink-2", "#000101" )
                , ( "--stone", "#020304" )
                , ( "--stone-2", "#07090a" )
                , ( "--stone-3", "#0f1112" )
                , ( "--stone-line", "#15181b" )
                , ( "--lapis", "#6a9eca" )
                , ( "--lapis-bright", "#9ecdf6" )
                , ( "--lapis-deep", "#3c6588" )
                , ( "--gold", "#7fa5b8" )
                , ( "--gold-bright", "#add1e3" )
                , ( "--gold-deep", "#516f7e" )
                , ( "--shu", "#e95047" )
                , ( "--shu-bright", "#ff7f72" )
                , ( "--paper", "#d6dfe7" )
                , ( "--paper-dim", "#9199a1" )
                , ( "--paper-mute", "#5a656e" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 30%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 12%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 12%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--paper) 5%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "1px" )
                , ( "--r-md", "3px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "220ms" )
                ]
        "pearl" ->
            Dict.fromList
                [ ( "--ink", "#f5f0e5" )
                , ( "--ink-2", "#f1ebe1" )
                , ( "--stone", "#e5e0d6" )
                , ( "--stone-2", "#dbd6cc" )
                , ( "--stone-3", "#d0cbc1" )
                , ( "--stone-line", "#c9c2b5" )
                , ( "--lapis", "#0065b0" )
                , ( "--lapis-bright", "#086fbe" )
                , ( "--lapis-deep", "#003e70" )
                , ( "--gold", "#896100" )
                , ( "--gold-bright", "#ad7c0a" )
                , ( "--gold-deep", "#5f4200" )
                , ( "--shu", "#c83319" )
                , ( "--shu-bright", "#e5462b" )
                , ( "--paper", "#251e15" )
                , ( "--paper-dim", "#494136" )
                , ( "--paper-mute", "#71675a" )
                , ( "--ok", "#15915c" )
                , ( "--warn", "var(--gold)" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--gold) 55%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--gold) 24%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--lapis) 28%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--lapis) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "4px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "200ms" )
                ]
        "ink" ->
            Dict.fromList
                [ ( "--ink", "#000001" )
                , ( "--ink-2", "#010102" )
                , ( "--stone", "#030405" )
                , ( "--stone-2", "#08090c" )
                , ( "--stone-3", "#0f1113" )
                , ( "--stone-line", "#15181c" )
                , ( "--lapis", "#c9c3bc" )
                , ( "--lapis-bright", "#ece7e0" )
                , ( "--lapis-deep", "#9d9892" )
                , ( "--gold", "#bbb7b1" )
                , ( "--gold-bright", "#dedad5" )
                , ( "--gold-deep", "#908c88" )
                , ( "--shu", "#d8412c" )
                , ( "--shu-bright", "#ff5d44" )
                , ( "--paper", "#f0eae2" )
                , ( "--paper-dim", "#a9a49c" )
                , ( "--paper-mute", "#706b63" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--paper) 16%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--paper) 7%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--lapis) 25%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--lapis) 10%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "0px" )
                , ( "--r-md", "2px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "180ms" )
                ]
        "shu" ->
            Dict.fromList
                [ ( "--ink", "#080100" )
                , ( "--ink-2", "#0b0201" )
                , ( "--stone", "#160705" )
                , ( "--stone-2", "#21100d" )
                , ( "--stone-3", "#2c1a17" )
                , ( "--stone-line", "#3a211c" )
                , ( "--lapis", "#e74142" )
                , ( "--lapis-bright", "#ff958d" )
                , ( "--lapis-deep", "#940014" )
                , ( "--gold", "#f4733c" )
                , ( "--gold-bright", "#ffb294" )
                , ( "--gold-deep", "#a43e08" )
                , ( "--shu", "#e9523b" )
                , ( "--shu-bright", "#ff806a" )
                , ( "--paper", "#ebdad5" )
                , ( "--paper-dim", "#a49490" )
                , ( "--paper-mute", "#725e59" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 16%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--shu) 18%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--shu) 8%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "4px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "hisui" ->
            Dict.fromList
                [ ( "--ink", "#000401" )
                , ( "--ink-2", "#000601" )
                , ( "--stone", "#040f06" )
                , ( "--stone-2", "#0c190f" )
                , ( "--stone-3", "#162319" )
                , ( "--stone-line", "#1b2e1f" )
                , ( "--lapis", "#00a149" )
                , ( "--lapis-bright", "#5bd47d" )
                , ( "--lapis-deep", "#005e28" )
                , ( "--gold", "#70c5a0" )
                , ( "--gold-bright", "#a5e9c9" )
                , ( "--gold-deep", "#3e8165" )
                , ( "--shu", "#e95146" )
                , ( "--shu-bright", "#ff7f71" )
                , ( "--paper", "#d6e2d8" )
                , ( "--paper-dim", "#919c92" )
                , ( "--paper-mute", "#5a685b" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 38%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 15%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--lapis) 22%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--lapis) 9%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "4px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "pine" ->
            Dict.fromList
                [ ( "--ink", "#000300" )
                , ( "--ink-2", "#010501" )
                , ( "--stone", "#060e05" )
                , ( "--stone-2", "#0e170d" )
                , ( "--stone-3", "#182116" )
                , ( "--stone-line", "#1e2c1b" )
                , ( "--lapis", "#3b9f32" )
                , ( "--lapis-bright", "#79d070" )
                , ( "--lapis-deep", "#065f00" )
                , ( "--gold", "#a5a51a" )
                , ( "--gold-bright", "#cdcf62" )
                , ( "--gold-deep", "#686800" )
                , ( "--shu", "#e95047" )
                , ( "--shu-bright", "#ff7f72" )
                , ( "--paper", "#d8e1d6" )
                , ( "--paper-dim", "#939b91" )
                , ( "--paper-mute", "#5c675a" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 38%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 15%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 11%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "3px" )
                , ( "--r-md", "7px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "250ms" )
                ]
        "kohaku" ->
            Dict.fromList
                [ ( "--ink", "#050200" )
                , ( "--ink-2", "#080300" )
                , ( "--stone", "#130b01" )
                , ( "--stone-2", "#1d1507" )
                , ( "--stone-3", "#281f11" )
                , ( "--stone-line", "#342812" )
                , ( "--lapis", "#d98b09" )
                , ( "--lapis-bright", "#ffb75d" )
                , ( "--lapis-deep", "#8a5600" )
                , ( "--gold", "#eea563" )
                , ( "--gold-bright", "#ffcca1" )
                , ( "--gold-deep", "#a46c36" )
                , ( "--shu", "#e85336" )
                , ( "--shu-bright", "#ff8066" )
                , ( "--paper", "#e4ddd0" )
                , ( "--paper-dim", "#9e988b" )
                , ( "--paper-mute", "#6a6252" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 36%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 15%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--lapis) 28%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--lapis) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "4px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "terracotta" ->
            Dict.fromList
                [ ( "--ink", "#060100" )
                , ( "--ink-2", "#0a0200" )
                , ( "--stone", "#140904" )
                , ( "--stone-2", "#1f130c" )
                , ( "--stone-3", "#2a1d16" )
                , ( "--stone-line", "#37241a" )
                , ( "--lapis", "#d55c27" )
                , ( "--lapis-bright", "#ff9970" )
                , ( "--lapis-deep", "#832e00" )
                , ( "--gold", "#e8777a" )
                , ( "--gold-bright", "#ffafae" )
                , ( "--gold-deep", "#9c4346" )
                , ( "--shu", "#e8523b" )
                , ( "--shu-bright", "#ff8069" )
                , ( "--paper", "#e8dbd4" )
                , ( "--paper-dim", "#a1968f" )
                , ( "--paper-mute", "#6f6057" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 16%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "4px" )
                , ( "--r-md", "9px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "vermillion" ->
            Dict.fromList
                [ ( "--ink", "#060100" )
                , ( "--ink-2", "#0a0101" )
                , ( "--stone", "#140604" )
                , ( "--stone-2", "#1d0f0b" )
                , ( "--stone-3", "#281814" )
                , ( "--stone-line", "#351e19" )
                , ( "--lapis", "#de5034" )
                , ( "--lapis-bright", "#ff9781" )
                , ( "--lapis-deep", "#8e1900" )
                , ( "--gold", "#ef7179" )
                , ( "--gold-bright", "#ffafb0" )
                , ( "--gold-deep", "#a13d46" )
                , ( "--shu", "#e95144" )
                , ( "--shu-bright", "#ff7f70" )
                , ( "--paper", "#eadad6" )
                , ( "--paper-dim", "#a39591" )
                , ( "--paper-mute", "#715e5a" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 16%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "3px" )
                , ( "--r-md", "6px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "sapphire" ->
            Dict.fromList
                [ ( "--ink", "#000208" )
                , ( "--ink-2", "#00040d" )
                , ( "--stone", "#020b16" )
                , ( "--stone-2", "#071420" )
                , ( "--stone-3", "#111e2b" )
                , ( "--stone-line", "#132739" )
                , ( "--lapis", "#0089ea" )
                , ( "--lapis-bright", "#7cbdff" )
                , ( "--lapis-deep", "#004f8b" )
                , ( "--gold", "#00aaf3" )
                , ( "--gold-bright", "#8ad1ff" )
                , ( "--gold-deep", "#006b9b" )
                , ( "--shu", "#e95047" )
                , ( "--shu-bright", "#ff7f72" )
                , ( "--paper", "#d4e0eb" )
                , ( "--paper-dim", "#8f9aa5" )
                , ( "--paper-mute", "#576573" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 40%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 16%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 12%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "2px" )
                , ( "--r-md", "5px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "teal" ->
            Dict.fromList
                [ ( "--ink", "#000302" )
                , ( "--ink-2", "#000603" )
                , ( "--stone", "#010f0a" )
                , ( "--stone-2", "#071914" )
                , ( "--stone-3", "#11241e" )
                , ( "--stone-line", "#122f26" )
                , ( "--lapis", "#009d82" )
                , ( "--lapis-bright", "#00d5b2" )
                , ( "--lapis-deep", "#005b4b" )
                , ( "--gold", "#72ccab" )
                , ( "--gold-bright", "#9feacd" )
                , ( "--gold-deep", "#42876e" )
                , ( "--shu", "#e95049" )
                , ( "--shu-bright", "#ff7f74" )
                , ( "--paper", "#d3e2dc" )
                , ( "--paper-dim", "#8e9c97" )
                , ( "--paper-mute", "#556861" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 36%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 15%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 14%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 11%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "6px" )
                , ( "--r-md", "13px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "260ms" )
                ]
        "slate" ->
            Dict.fromList
                [ ( "--ink", "#040301" )
                , ( "--ink-2", "#060503" )
                , ( "--stone", "#110e0a" )
                , ( "--stone-2", "#1c1a15" )
                , ( "--stone-3", "#282521" )
                , ( "--stone-line", "#343029" )
                , ( "--lapis", "#949d7b" )
                , ( "--lapis-bright", "#bdc6a5" )
                , ( "--lapis-deep", "#656c51" )
                , ( "--gold", "#ae7853" )
                , ( "--gold-bright", "#d8a582" )
                , ( "--gold-deep", "#73492b" )
                , ( "--shu", "#e9523c" )
                , ( "--shu-bright", "#ff806a" )
                , ( "--paper", "#eae7e2" )
                , ( "--paper-dim", "#a7a49e" )
                , ( "--paper-mute", "#716e68" )
                , ( "--ok", "#5bc78e" )
                , ( "--warn", "#e6d08c" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 28%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 12%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 13%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--lapis) 10%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "4px" )
                , ( "--r-md", "9px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "240ms" )
                ]
        "frost" ->
            Dict.fromList
                [ ( "--ink", "#e3f7fe" )
                , ( "--ink-2", "#def2f8" )
                , ( "--stone", "#d0e4ea" )
                , ( "--stone-2", "#c3d7dd" )
                , ( "--stone-3", "#b6cad0" )
                , ( "--stone-line", "#a4c0c8" )
                , ( "--lapis", "#036884" )
                , ( "--lapis-bright", "#2f7791" )
                , ( "--lapis-deep", "#003c4d" )
                , ( "--gold", "#00768a" )
                , ( "--gold-bright", "#0096af" )
                , ( "--gold-deep", "#00515f" )
                , ( "--shu", "#c92f34" )
                , ( "--shu-bright", "#e64344" )
                , ( "--paper", "#202b2e" )
                , ( "--paper-dim", "#546063" )
                , ( "--paper-mute", "#7a8d92" )
                , ( "--ok", "#15915c" )
                , ( "--warn", "#8a6e1f" )
                , ( "--danger", "var(--shu)" )
                , ( "--seam", "color-mix(in oklab, var(--lapis) 34%, transparent)" )
                , ( "--seam-faint", "color-mix(in oklab, var(--lapis) 14%, transparent)" )
                , ( "--line", "color-mix(in oklab, var(--paper) 18%, transparent)" )
                , ( "--line-faint", "color-mix(in oklab, var(--gold) 14%, transparent)" )
                , ( "--r-0", "0px" )
                , ( "--r-sm", "5px" )
                , ( "--r-md", "10px" )
                , ( "--r-pill", "999px" )
                , ( "--ease", "cubic-bezier(0.16, 1, 0.3, 1)" )
                , ( "--dur", "220ms" )
                ]

        _ ->
            Dict.empty
